# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "<Enter a description>"
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
    lane :android_beta_app do
        firebase_app_distribution(
            app: "1:979286389145:android:dd303a0d30b1aa4c322308",
            testers: "remidormoy9@gmail.com, rdormoy@octo.com",
            release_notes: "Bonjour je suis une release note",
            firebase_cli_path: "/usr/local/bin/firebase",
            firebase_cli_token: "1//03tiH7Cd7vtF8CgYIARAAGAMSNwF-L9IrCcUhREJb1Amt4TeAUf_JibFz4vSfmTApnIWAJQcQd4I3dU4AEJ4-A8KzirZItaCQIuE",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end
end